// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/gobang.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 棋子类型
type ChessType int32

const (
	ChessType_EMPTY ChessType = 0
	ChessType_BLACK ChessType = 1
	ChessType_WHITE ChessType = 2
)

// Enum value maps for ChessType.
var (
	ChessType_name = map[int32]string{
		0: "EMPTY",
		1: "BLACK",
		2: "WHITE",
	}
	ChessType_value = map[string]int32{
		"EMPTY": 0,
		"BLACK": 1,
		"WHITE": 2,
	}
)

func (x ChessType) Enum() *ChessType {
	p := new(ChessType)
	*p = x
	return p
}

func (x ChessType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChessType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gobang_proto_enumTypes[0].Descriptor()
}

func (ChessType) Type() protoreflect.EnumType {
	return &file_proto_gobang_proto_enumTypes[0]
}

func (x ChessType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChessType.Descriptor instead.
func (ChessType) EnumDescriptor() ([]byte, []int) {
	return file_proto_gobang_proto_rawDescGZIP(), []int{0}
}

// 消息类型枚举
type MsgType int32

const (
	MsgType_MSG_WAIT          MsgType = 0  // 等待对手
	MsgType_MSG_START         MsgType = 1  // 对局开始
	MsgType_MSG_PUT           MsgType = 2  // 落子
	MsgType_MSG_WIN           MsgType = 3  // 分出胜负
	MsgType_MSG_TIP           MsgType = 4  // 普通提示消息
	MsgType_MSG_LOGIN_REQ     MsgType = 5  // 登录请求
	MsgType_MSG_QUIT_GAME     MsgType = 6  // 主动退出对局
	MsgType_MSG_LOGIN_RESP    MsgType = 7  // 登录响应
	MsgType_MSG_REGISTER_REQ  MsgType = 8  // 注册请求
	MsgType_MSG_REGISTER_RESP MsgType = 9  // 注册响应
	MsgType_MSG_MATCH_REQ     MsgType = 10 // 匹配请求
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0:  "MSG_WAIT",
		1:  "MSG_START",
		2:  "MSG_PUT",
		3:  "MSG_WIN",
		4:  "MSG_TIP",
		5:  "MSG_LOGIN_REQ",
		6:  "MSG_QUIT_GAME",
		7:  "MSG_LOGIN_RESP",
		8:  "MSG_REGISTER_REQ",
		9:  "MSG_REGISTER_RESP",
		10: "MSG_MATCH_REQ",
	}
	MsgType_value = map[string]int32{
		"MSG_WAIT":          0,
		"MSG_START":         1,
		"MSG_PUT":           2,
		"MSG_WIN":           3,
		"MSG_TIP":           4,
		"MSG_LOGIN_REQ":     5,
		"MSG_QUIT_GAME":     6,
		"MSG_LOGIN_RESP":    7,
		"MSG_REGISTER_REQ":  8,
		"MSG_REGISTER_RESP": 9,
		"MSG_MATCH_REQ":     10,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_gobang_proto_enumTypes[1].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_proto_gobang_proto_enumTypes[1]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_proto_gobang_proto_rawDescGZIP(), []int{1}
}

// 对局通信统一消息体
type GameMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgType       MsgType                `protobuf:"varint,1,opt,name=msg_type,json=msgType,proto3,enum=gobang.MsgType" json:"msg_type,omitempty"`
	Chess         ChessType              `protobuf:"varint,2,opt,name=chess,proto3,enum=gobang.ChessType" json:"chess,omitempty"` // 当前棋子/己方棋子
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Tip           string                 `protobuf:"bytes,5,opt,name=tip,proto3" json:"tip,omitempty"`
	Username      string                 `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	UserId        int32                  `protobuf:"varint,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VsBot         bool                   `protobuf:"varint,9,opt,name=vs_bot,json=vsBot,proto3" json:"vs_bot,omitempty"` // 是否匹配人机
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMsg) Reset() {
	*x = GameMsg{}
	mi := &file_proto_gobang_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMsg) ProtoMessage() {}

func (x *GameMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gobang_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMsg.ProtoReflect.Descriptor instead.
func (*GameMsg) Descriptor() ([]byte, []int) {
	return file_proto_gobang_proto_rawDescGZIP(), []int{0}
}

func (x *GameMsg) GetMsgType() MsgType {
	if x != nil {
		return x.MsgType
	}
	return MsgType_MSG_WAIT
}

func (x *GameMsg) GetChess() ChessType {
	if x != nil {
		return x.Chess
	}
	return ChessType_EMPTY
}

func (x *GameMsg) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *GameMsg) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *GameMsg) GetTip() string {
	if x != nil {
		return x.Tip
	}
	return ""
}

func (x *GameMsg) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GameMsg) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GameMsg) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GameMsg) GetVsBot() bool {
	if x != nil {
		return x.VsBot
	}
	return false
}

var File_proto_gobang_proto protoreflect.FileDescriptor

const file_proto_gobang_proto_rawDesc = "" +
	"\n" +
	"\x12proto/gobang.proto\x12\x06gobang\"\xf4\x01\n" +
	"\aGameMsg\x12*\n" +
	"\bmsg_type\x18\x01 \x01(\x0e2\x0f.gobang.MsgTypeR\amsgType\x12'\n" +
	"\x05chess\x18\x02 \x01(\x0e2\x11.gobang.ChessTypeR\x05chess\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x10\n" +
	"\x03tip\x18\x05 \x01(\tR\x03tip\x12\x1a\n" +
	"\busername\x18\x06 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\x12\x17\n" +
	"\auser_id\x18\b \x01(\x05R\x06userId\x12\x15\n" +
	"\x06vs_bot\x18\t \x01(\bR\x05vsBot*,\n" +
	"\tChessType\x12\t\n" +
	"\x05EMPTY\x10\x00\x12\t\n" +
	"\x05BLACK\x10\x01\x12\t\n" +
	"\x05WHITE\x10\x02*\xc7\x01\n" +
	"\aMsgType\x12\f\n" +
	"\bMSG_WAIT\x10\x00\x12\r\n" +
	"\tMSG_START\x10\x01\x12\v\n" +
	"\aMSG_PUT\x10\x02\x12\v\n" +
	"\aMSG_WIN\x10\x03\x12\v\n" +
	"\aMSG_TIP\x10\x04\x12\x11\n" +
	"\rMSG_LOGIN_REQ\x10\x05\x12\x11\n" +
	"\rMSG_QUIT_GAME\x10\x06\x12\x12\n" +
	"\x0eMSG_LOGIN_RESP\x10\a\x12\x14\n" +
	"\x10MSG_REGISTER_REQ\x10\b\x12\x15\n" +
	"\x11MSG_REGISTER_RESP\x10\t\x12\x11\n" +
	"\rMSG_MATCH_REQ\x10\n" +
	"B\tZ\a./pb;pbb\x06proto3"

var (
	file_proto_gobang_proto_rawDescOnce sync.Once
	file_proto_gobang_proto_rawDescData []byte
)

func file_proto_gobang_proto_rawDescGZIP() []byte {
	file_proto_gobang_proto_rawDescOnce.Do(func() {
		file_proto_gobang_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gobang_proto_rawDesc), len(file_proto_gobang_proto_rawDesc)))
	})
	return file_proto_gobang_proto_rawDescData
}

var file_proto_gobang_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_gobang_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_gobang_proto_goTypes = []any{
	(ChessType)(0),  // 0: gobang.ChessType
	(MsgType)(0),    // 1: gobang.MsgType
	(*GameMsg)(nil), // 2: gobang.GameMsg
}
var file_proto_gobang_proto_depIdxs = []int32{
	1, // 0: gobang.GameMsg.msg_type:type_name -> gobang.MsgType
	0, // 1: gobang.GameMsg.chess:type_name -> gobang.ChessType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_gobang_proto_init() }
func file_proto_gobang_proto_init() {
	if File_proto_gobang_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gobang_proto_rawDesc), len(file_proto_gobang_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_gobang_proto_goTypes,
		DependencyIndexes: file_proto_gobang_proto_depIdxs,
		EnumInfos:         file_proto_gobang_proto_enumTypes,
		MessageInfos:      file_proto_gobang_proto_msgTypes,
	}.Build()
	File_proto_gobang_proto = out.File
	file_proto_gobang_proto_goTypes = nil
	file_proto_gobang_proto_depIdxs = nil
}
